config/routes.rb
Robopot::Application.routes.draw do
  resources :pot_data

  match 'get_level' => 'pot_data#get_level'
  match 'get_potdata' => 'pot_data#get_potdata'

  root :to => 'pot_data#index'

end

app/models/pot_datum.rb
class PotDatum < ActiveRecord::Base
  attr_accessible :level

  before_save :scale_level

  private

  def scale_level
    #raw = self.level
    #self.level = (raw - 150)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pot_data_controller.rb
class PotDataController < ApplicationController
  # GET /pot_data
  # GET /pot_data.json
  def index
  end

  def get_level
    level = PotDatum.last.level / 5
    #level = 10.0 if level > 10.0
    #level = 0.0 if level < 0.0
    render json: {level: level}
  end

  def get_potdata
    if params[:duration].nil?
      Thread.current[:duration] ||= 3600
    else
      Thread.current[:duration] = params[:duration].to_i
    end
    duration = Thread.current[:duration]
    interval = (duration / 500).to_i
    start_time = Time.now - duration
    puts duration, interval, start_time

    @data = PotDatum.where('created_at > ?', start_time).where('id % ? = 0', interval)
    data_a = [['Time', 'Level']] + @data.map{|d| [d.created_at, d.level]}
    render json: {data_array: data_a, duration: duration  }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pot_data_helper.rb
module PotDataHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Robopot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pot_data/_cup_gauge.html.erb
<%= javascript_tag do %>
    google.load('visualization', '1', {packages:['gauge']});
    google.setOnLoadCallback(drawGauge);

    function drawGauge() {
        var data = google.visualization.arrayToDataTable([
            ['Label', 'Value'],
            ['Cups Left', 0]
        ]);

        var options = {
            width: 500,
            height: 500,
            //animation: {duration: 400, easing: 'inAndOut'},
            backgroundColor: { fill: "none" },
            majorTicks: ['0',2,4,6,8,10],
            minorTicks: 2,
            min: 0,
            max: 10,
            redFrom: 0,
            redTo: 2,
            yellowFrom: 2,
            yellowTo: 8,
            greenFrom: 8,
            greenTo: 10
        };

        var chart = new google.visualization.Gauge(document.getElementById('gauge_div'));
        chart.draw(data, options);

    setInterval(get_level, 1000);
    function get_level(){
    jQuery.get("/get_level", function(level_hash) {
    console.log(level_hash.level);
    data.setValue(0,1, level_hash.level);
    chart.draw(data, options);

    });
    };

        }


<% end %>

<td id='gauge_div' />

app/views/pot_data/_form.html.erb
<%= form_for(@pot_datum) do |f| %>
  <% if @pot_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pot_datum.errors.count, "error") %> prohibited this pot_datum from being saved:</h2>

      <ul>
      <% @pot_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pot_data/_time_plot.html.erb
<%= javascript_tag do %>
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(get_potdata);
    setInterval(get_potdata, 2000);

    function drawPlot(potdata) {
        var data = google.visualization.arrayToDataTable(potdata);
        var options = {
            title: 'Is the lovely pot empty?',
            width: 1200,
            height: 500,
            backgroundColor: { fill: "none" },
            curveType: 'function'
        };

        var chart = new google.visualization.LineChart(document.getElementById('plot_div'));
        chart.draw(data, options);
    }

    function get_potdata(){
        jQuery.get("/get_potdata", function(potdata) {
            drawPlot(potdata.data_array);
        });
    };

    function update_range(range){
        jQuery.get("/get_potdata", {duration: range}, function(potdata) {
            drawPlot(potdata.data_array);
        });
    };
<% end %>

<td>
  <table>
    <tr>
      <td align="right">
        <%= button_to_function '30m', "update_range(1800)" %>
        <%= button_to_function '1H', "update_range(3600)" %>
        <%= button_to_function '6H', "update_range(21600)" %>
        <%= button_to_function '12H', "update_range(43200)" %>
        <%= button_to_function '1D', "update_range(86400)" %>
        <%= button_to_function '1W', "update_range(604800)" %>
      </td>
      </tr>
    <tr>
      <td id='plot_div' />
    </tr>
  </table>
</td>

app/views/pot_data/edit.html.erb
<h1>Editing pot_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @pot_datum %> |
<%= link_to 'Back', pot_data_path %>

app/views/pot_data/index.html.erb
<%= stylesheet_link_tag 'pot_data' %>

<h1 align='center'>RoboPot</h1>

<table align='center'>
  <tr>
    <%= render partial: 'cup_gauge' %>
    <%= render partial: 'time_plot' %>
  </tr>
</table>

app/views/pot_data/new.html.erb
<h1>New pot_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', pot_data_path %>

app/views/pot_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Level:</b>
  <%= @pot_datum.level %>
</p>


<%= link_to 'Edit', edit_pot_datum_path(@pot_datum) %> |
<%= link_to 'Back', pot_data_path %>